name: ShortLifePlugin
version: '${version}'
main: dev.felnull.shortlifeplugin.ShortLifePlugin
api-version: '1.20'
authors: [ MORIMORI0317, FelNull Developers ]
description : The ikisugi gun server plugin...