name: ShortLifePlugin
version: '${version}'
main: dev.felnull.shortlifeplugin.ShortLifePlugin
api-version: '1.20'
authors: [ MORIMORI0317, nin8995]
contributors: [ FelNull Developers ]
description: The ikisugi gun server plugin...
depend: [ WorldEdit ]

permissions:
  shortlifeplugin.commands.match:
    description: "Match command permission"
    default: op