name: ShortLifePlugin
version: '${version}'
main: dev.felnull.shortlifeplugin.ShortLifePlugin
api-version: '1.20'
authors: [ MORIMORI0317, nin8995, miyabi0333 ]
contributors: [ FelNull Developers ]
description: The ikisugi gun server plugin...
depend: [ WorldEdit, WorldGuard, CommandAPI, WeaponMechanics ]

permissions:
  shortlifeplugin.commands.match:
    description: "Match command permission"
    default: op
  shortlifeplugin.commands.gui:
    description: "GUI command permission"
    default: op
  shortlifeplugin.commands.equipmentgroup:
    description: "Equipment Group command permission"
    default: op
  shortlifeplugin.commands.room:
    description: "Room command permission"
    default: true